import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{backgroundColor:'pink',padding:'20px',marginBottom:'50px'}}>This is header</header>
        {children}
        <footer style={{backgroundColor:'pink',padding:'20px',marginTop:'50px'}}>This is footer</footer>
      </body>
    </html>
  );
}
